spring:
  application:
    name: java-initializr
  main:
    allow-bean-definition-overriding: true
  rabbitmq: 
    host: rabbitmq-serverless-cn-27a3jk1lz0a.cn-hangzhou.amqp-15.net.mq.amqp.aliyuncs.com
    port: 5672
    username: MjpyYWJiaXRtcS1zZXJ2ZXJsZXNzLWNuLTI3YTNqazFsejBhOkxUQUk1dEtaTHA0NlV5U3pTVEZITFBOVw==
    password: MjJEOTQ1NUMwMTZGQzRGNzZFMEExRjQ0ODM0NUVBMzlDQTZDRDlDOToxNzAzNzU1MTE2MzU1
    virtual-host: mishu-oms-test
    listener.simple.acknowledge-mode: manual
    dynamic: true
    prefetch:
      count: 1
    concurrent:
      consumers: 1
    max:
      concurrent:
        consumers: 1
server:
  port: 8080

app:
  id: ${spring.application.name}

apollo:
  meta: http://127.0.0.1:9000
  bootstrap:
    enabled: false
    namespaces: application

eureka:
  client:
    enabled: false
    
